apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: lukssantanna/argocd
  newTag: 596b519ab731ba5ccd9fff748cc1263f18790e2b
